version: '3.7'

services:
  postgres:
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - identityforge-postgres:/var/lib/postgresql/data

  identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dotnet-devcert.pfx
    ports:
      - "5100:80"
      - "5101:443"
    volumes:
      - ${HOME}/.aspnet/https:/https/:ro
      - ./:/app

volumes:
  identityforge-postgres:
    external: false