version: '3.7'

services:
  postgres:
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - eiromplays-admin-postgres:/var/lib/postgresql/data
    networks:
      eiromplays-identityserver: null

  nginx-proxy:
    restart: always
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - './shared/nginx/vhost.d:/etc/nginx/vhost.d'
      - './shared/nginx/certs:/etc/nginx/certs:ro'
    networks:
      proxy: null
      eiromplays-identityserver:
        aliases:
          - auth.eiromplays.local.com
          - api.eiromplays.local.com
          - admin.eiromplays.local.com
          - web.eiromplays.local.com

  identityserver:
    container_name: auth.eiromplays.local.com
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;
      - PORT=80
      - VIRTUAL_HOST=auth.eiromplays.local.com
      - DatabaseConfiguration__ConnectionStringsConfiguration__ApplicationDbConnection=${EIROMPLAYS_ADMIN_IDENTITYSERVER_DB:-Server=postgres;Database=EiromplaysIdentityServer;User Id=postgres;Password=1234}
      - DatabaseConfiguration__ConnectionStringsConfiguration__SessionDbConnection=${EIROMPLAYS_ADMIN_IDENTITYSERVER_DB:-Server=postgres;Database=EiromplaysIdentityServer;User Id=postgres;Password=1234}
      - HangfireSettings__Storage__ConnectionString=${EIROMPLAYS_ADMIN_IDENTITYSERVER_DB:-Server=postgres;Database=EiromplaysIdentityServer;User Id=postgres;Password=1234}
    ports:
      - "7001:80"
    volumes:
      - ./:/app
    networks:
      eiromplays-identityserver: null

  api:
    container_name: eiromplays-identityserver-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;
      - PORT=80
      - VIRTUAL_HOST=api.eiromplays.local.com
      - DatabaseConfiguration__ConnectionStringsConfiguration__ApplicationDbConnection=${EIROMPLAYS_ADMIN_IDENTITYSERVER_DB:-Server=postgres;Database=EiromplaysIdentityServer;User Id=postgres;Password=1234}
      - DatabaseConfiguration__ConnectionStringsConfiguration__SessionDbConnection=${EIROMPLAYS_ADMIN_IDENTITYSERVER_DB:-Server=postgres;Database=EiromplaysIdentityServer;User Id=postgres;Password=1234}
      - HangfireSettings__Storage__ConnectionString=${EIROMPLAYS_ADMIN_IDENTITYSERVER_DB:-Server=postgres;Database=EiromplaysIdentityServer;User Id=postgres;Password=1234}
    ports:
      - "7003:80"
    volumes:
      - ./:/app
    networks:
      eiromplays-identityserver: null

  admin-ui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=Microsoft.AspNetCore.SpaProxy
      - ASPNETCORE_URLS=http://+:80;
      - PORT=80
      - VIRTUAL_HOST=admin.eiromplays.local.com
      - DatabaseConfiguration__ConnectionStringsConfiguration__SessionDbConnection=${EIROMPLAYS_ADMIN_IDENTITYSERVER_DB:-Server=postgres;Database=EiromplaysIdentityServer;User Id=postgres;Password=1234}
    ports:
      - "7004:80"
      - "3001:3001"
    volumes:
      - ./:/app
    networks:
      eiromplays-identityserver: null

  web-ui:
    container_name: web.eiromplays.local.com
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=Microsoft.AspNetCore.SpaProxy
      - ASPNETCORE_URLS=http://+:80;
      - PORT=80
      - VIRTUAL_HOST=web.eiromplays.local.com
      - DatabaseConfiguration__ConnectionStringsConfiguration__SessionDbConnection=${EIROMPLAYS_ADMIN_IDENTITYSERVER_DB:-Server=postgres;Database=EiromplaysIdentityServer;User Id=postgres;Password=1234}
      - PROXY_TARGET=http://web.eiromplays.local.com
      - UrlsConfiguration__IdentityServerBaseUrl=http://auth.eiromplays.local.com
      - UrlsConfiguration__ApiBaseUrl=http://api:80
    ports:
      - "7002:80"
      - "3000:3000"
    volumes:
      - ./:/app
    networks:
      eiromplays-identityserver: null

volumes:
  eiromplays-admin-postgres:
    external: false

networks:
  proxy:
    driver: bridge
  eiromplays-identityserver:
      driver: bridge