version: '3.7'

services:
  postgres:
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - eiromplays-admin-postgres:/var/lib/postgresql/data

volumes:
  eiromplays-admin-postgres:
    external: false