version: '3.7'
name: eiromplays-identityserver-admin

services:
  postgres:
    image: postgres:14.4-alpine

  identityserver:
    build:
      context: .
      dockerfile: Presentation/Eiromplays.IdentityServer/Dockerfile
    depends_on:
      - postgres