version: '3.7'

services:
  postgres:
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - eiromplays-admin-postgres:/var/lib/postgresql/data

  identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:443
      - PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Docker1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/docker.pfx
    ports:
      - "7001:443"
    volumes:
      - ~/.aspnet/https:/https:ro
      - ./:/app

volumes:
  eiromplays-admin-postgres:
    external: false